from core.acciones.admin import *
from core.cartera_comercial.admin import *
from core.clientes.admin import *
from core.comerciales.admin import *
from core.compras.admin import *
from core.leads.admin import *
from core.perfiles.admin import *
from core.productos.admin import *
from core.proveedores.admin import *
from core.tipos_accion.admin import *
from core.ventas.admin import *
